name: Run Postman API tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman GitHub reporter
        run: npm install -g newman-reporter-github

      - name: Install backend dependencies
        run: dotnet restore
        working-directory: server

      - name: Build backend
        run: dotnet build --configuration Release
        working-directory: server

      - name: Start API-server
        run: dotnet run &
        working-directory: server

      - name: Wait for server to start
        run: sleep 5

      - name: Run API tests with Newman
        run: |
          newman run postman/ShopTester-testflows.postman_collection.json \
          --environment postman/shoptester.postman_environment.json \
          --reporters cli,github \
          --reporter-json-export newman-report.json
