name: Run Postman API tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests with Newman
        run: |
          newman run postman/ShopTester-testflows.postman_collection.json \
          --environment postman/shoptester.postman_environment.json \
          --reporters cli,github \
          --reporter-json-export newman-report.json
