name: Run Postman API tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install Newman
        run: npm install -g newman

      - name: Install dotnet project dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Start API-server
        run: cd server && nohup dotnet run &

      - name: Wait for API to start
        run: sleep 5

      - name: Run API tests with Newman
        run: |
          newman run postman/ShopTester-testflows.postman_collection.json \
          --environment postman/shoptester.postman_environment.json \
          --reporters cli \
          --reporter-json-export newman-report.json
